name: BlockBattle
version: '${project.version}'
main: me.reversee.blockbattle.Blockbattle
api-version: 1.19
authors: [ reversee ]
description: block battle implementation

commands:
  arena:
    description: Arena Manager Command
    usage: /arena <create|delete|start|stop|list|add_player|remove_player|clean>
    alias: []
    permissions: blockbattle.arena

permissions:
  blockbattle.arena:
    description: Allow using /arena command
    default: op